import React, { useEffect, useState } from "react";
import axios from "axios";
import { messageErreur, urlPublic } from "../../../api/api";
import { urlQr, maj } from "../CartesEleves/outilsCarte";

const payloadPersonnel = (agent) => JSON.stringify({ type: "personnel", id: agent?.id, matricule: agent?.matricule || agent?.email, nom: [agent?.name, agent?.last_name, agent?.first_name].filter(Boolean).join(" "), role: agent?.fonction?.name || agent?.role, ecole_id: agent?.ecole_id || localStorage.getItem("ecole_id"), direction: agent?.direction || localStorage.getItem("direction") });

const CartesPersonnel = ({ cycle, BarreGauche, NavHaut }) => {
  const [agents, setAgents] = useState([]); const [ids, setIds] = useState([]); const [chargement, setChargement] = useState(true); const [erreur, setErreur] = useState("");
  const ecoleId = localStorage.getItem("ecole_id"); const direction = localStorage.getItem("direction");
  useEffect(() => { const charger = async () => { setChargement(true); setErreur(""); try { const res = await axios.get(`/user/all/ecole/${ecoleId}/direction/${direction}`); setAgents(res.data.users || res.data.userAll || res.data.admins || []); } catch (err) { setErreur(messageErreur(err, "Impossible de charger le personnel.")); } finally { setChargement(false); } }; charger(); }, [ecoleId, direction]);
  const selection = agents.filter((a) => ids.includes(String(a.id)));
  const basculer = (id) => setIds((v) => v.includes(String(id)) ? v.filter((x) => x !== String(id)) : [...v, String(id)]);
  return <div className="container-fluid position-relative d-flex p-0 page-cartes-personnel"><BarreGauche /><div className="content"><NavHaut /><main className="container-fluid pt-4 px-4"><section className="cmd-cartes rounded p-4"><div className="d-flex justify-content-between flex-wrap gap-2"><div><h5>Cartes du personnel QR</h5><p className="text-muted">Cartes professionnelles avec QR code pour le pointage de présence.</p></div><button className="btn" onClick={() => window.print()} disabled={!selection.length}>Imprimer la sélection</button></div>{chargement && <div className="alert alert-info">Chargement du personnel...</div>}{erreur && <div className="alert alert-danger">{erreur}</div>}<div className="table-responsive mt-3"><table className="table"><thead><tr><th>Choix</th><th>Nom</th><th>Rôle</th><th>Email</th></tr></thead><tbody>{agents.map((a) => <tr key={a.id}><td><input type="checkbox" checked={ids.includes(String(a.id))} onChange={() => basculer(a.id)} /></td><td>{a.name} {a.last_name} {a.first_name}</td><td>{a.fonction?.name || a.role}</td><td>{a.email}</td></tr>)}</tbody></table></div></section><section className="zone-cartes zone-cartes-personnel mt-4">{selection.map((a) => <article className="carte-personnel-pro" key={a.id}><div className="carte-personnel-top"><div><span>ECOLAPP</span><h3>{maj(a.fonction?.name || a.role || "Personnel")}</h3></div><img src={urlQr(payloadPersonnel(a), 118)} alt="QR présence personnel" /></div><div className="carte-personnel-body">{a.file && <img className="photo-personnel" src={urlPublic(`public/imgUser/${a.file}`)} alt="Personnel" />}<div><h4>{maj(`${a.name || ""} ${a.last_name || ""}`)}</h4><p>{a.first_name}</p><p>{a.email || a.telephone}</p><small>QR code personnel pour arrivée et départ journaliers.</small></div></div></article>)}</section></main></div></div>;
};
export default CartesPersonnel;
