import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all files generated by the build
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache API requests
registerRoute(
  ({ url }) => url.origin === 'https://api.ecolapp.cd',
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50, // Maximum 50 requests in cache
        maxAgeSeconds: 5 * 60, // Expiration: 5 minutes
      }),
    ],
  })
);

// Cache images with a CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20, // Maximum 20 images
        maxAgeSeconds: 30 * 24 * 60 * 60, // Expiration: 30 days
      }),
    ],
  })
);

// Intercept all requests to handle offline requests
addEventListener('fetch', (event) => {
  const { request } = event;

  event.respondWith(
    fetch(request)
      .catch(async () => {
        console.log('[Service Worker] Recording offline request:', request.url);
        const db = await openIndexedDB();
        const data = {
          url: request.url,
          method: request.method,
          body: request.method !== 'GET' ? await request.clone().text() : null,
          headers: Object.fromEntries(request.headers.entries()),
          timestamp: Date.now(),
        };

        await db.put('requests', data);
        return new Response(JSON.stringify({ message: 'Data saved for synchronization' }), { status: 503 });
      })
  );
});

// Sync stored requests as soon as the connection is back
addEventListener('sync', (event) => {
  if (event.tag === 'sync-requests') {
    event.waitUntil(sendStoredRequests());
  }
});

// Function to open IndexedDB
async function openIndexedDB() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('pwa-db', 1);

    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains('requests')) {
        db.createObjectStore('requests', { keyPath: 'id', autoIncrement: true });
      }
    };

    request.onsuccess = (event) => resolve(event.target.result);
    request.onerror = (event) => reject(event.target.error);
  });
}

// Function to send stored offline requests
async function sendStoredRequests() {
  const db = await openIndexedDB();
  const transaction = db.transaction('requests', 'readonly');
  const store = transaction.objectStore('requests');
  const requests = await store.getAll();

  for (const req of requests) {
    try {
      await fetch(req.url, {
        method: req.method,
        headers: req.headers,
        body: req.body,
      });

      // If the request succeeds, delete it from the database
      const deleteTransaction = db.transaction('requests', 'readwrite');
      deleteTransaction.objectStore('requests').delete(req.id);
      await deleteTransaction.complete;

      console.log('[Service Worker] Request sent successfully:', req.url);
    } catch (error) {
      console.log('[Service Worker] Failed to send, will retry later:', req.url);
    }
  }
}
